name: Python Pylint

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose pylint target
        required: true
        type: choice
        default: all
        options:
          - all
          - specific

jobs:
  run-pylint:
    runs-on: windows-latest
    name: Run pylint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Install pylint
        run: |
          pip install pylint
      
      - name: Run pylint on all files
        if: github.event.inputs.deployment_target == 'all'
        run: |
          pylint **/*.py

      - name: Run pylint on specific files
        if: github.event.inputs.deployment_target == 'specific'
        run: |
          pylint path/to/specific_file.py
